(:PARAMETERS
 ((:P1 :SHORT-DOC "nix" :LONG-DOC "nixnix" :DATA
   (:TYPE :SCALAR :DATA 0.0 :LOWER-BORDER NIL :UPPER-BORDER NIL) :DEFAULT-DATA
   (:TYPE :SCALAR :DATA 0.0 :LOWER-BORDER NIL :UPPER-BORDER NIL))
  (:PX :SHORT-DOC "nix" :LONG-DOC "nixnix" :DATA
   (:TYPE :SCALAR :DATA 0.0 :LOWER-BORDER NIL :UPPER-BORDER NIL) :DEFAULT-DATA
   (:TYPE :SCALAR :DATA 0.0 :LOWER-BORDER NIL :UPPER-BORDER NIL))
  (:P2 :SHORT-DOC "nix1" :LONG-DOC "nixnix1" :DATA
   (:TYPE :SCALAR :DATA 1.0 :LOWER-BORDER NIL :UPPER-BORDER NIL) :DEFAULT-DATA
   (:TYPE :SCALAR :DATA 1.0 :LOWER-BORDER NIL :UPPER-BORDER NIL))
  (:TS :SHORT-DOC "test-string" :LONG-DOC "testing a string" :DATA
   (:TYPE :STRING :DATA "hi") :DEFAULT-DATA (:TYPE :STRING :DATA "[default]"))))