(in-package :arcimoog.symbolic-intervals)

(defparameter *mirabile* '((:bassus
                            (:s :brevis :word)
                            (:s :semibrevis :dot :sillable)
                            (:i :tono :➘)
                            (:s :minima :sillable)
                            (:s :brevis :sillable)
                            (:i :semitono-maggiore :➘)
                            (:s :brevis :sillable)
                            (:t :longa :dot)
                            ;; bar 8
                            (:t :semibrevis)
                            (:i :tono :➘)
                            (:s :semibrevis)
                            (:s :semibrevis :dot)
                            (:s :minima)
                            ;; bar 10
                            (:i :tono :➘)
                            (:s :brevis)
                            (:t :minima)
                            (:i :sesta-maggiore)
                            (:s :minima :dot)
                            (:i :tono :➘)
                            (:s :semiminima)
                            (:i :tono :➘)
                            (:s :semiminima)
                            (:i :semitono-maggiore :➘)
                            (:s :semiminima)
                            ;; bar 12
                            (:i :tono :➘)
                            (:s :minima)
                            (:i :tono :➘)
                            (:s :minima)
                            (:i :quarta)
                            (:s :semibrevis)
                            ;; bar 13
                            (:i :semitono-maggiore :➘)
                            (:s :minima :dot)
                            (:i :semitono-maggiore)
                            (:s :semiminima)
                            (:i :tono)
                            (:s :semibrevis)
                            ;; bar 14
                            (:i :tono :➘)
                            (:s :minima :dot)
                            (:i :semitono-maggiore :➘)
                            (:s :semiminima)
                            (:i :tono :➘)
                            (:s :minima)
                            (:i :tono :➘)
                            (:s :minima)
                            ;; bar 15
                            (:i :quarta)
                            (:s :semibrevis)
                            ;; delcaratur ...
                            (:t :semibrevis)
                            (:t :minima)
                            ()
                            )
                           (:tenor
                            (:s :brevis :word)
                            (:i :terza-minore)
                            (:s :semibrevis :dot :sillable)
                            (:i :semitono-maggiore :➘)
                            (:s :minima :sillable)
                            (:s :brevis :sillable)
                            (:t :semibrevis)
                            (:i :tono :➘)
                            (:s :brevis)
                            (:i :terza-minore)
                            (:s :semibrevis :dot)
                            (:i :semitono-maggiore :➘)
                            (:s :minima)
                            (:s :brevis)
                            (:i :tono :➘)
                            (:s :brevis)
                            (:i :tono :➘)
                            (:s :brevis)
                            (:i :terza-maggiore)
                            (:s :semibrevis :dot)
                            (:i :tono :➘)
                            (:s :semiminima)
                            (:i :tono :➘)
                            (:s :semiminima)
                            (:i :tono)
                            (:s :minima)
                            (:s :minima)
                            ;; bar 11
                            (:i :tono :➘)
                            (:s :semibrevis)
                            (:t :minima)
                            (:i :terza-maggiore)
                            (:s :semibrevis)
                            (:i :terza-minore)
                            (:s :semibrevis)
                            (:i :semitono-maggiore :➘)
                            (:s :semiminima)
                            (:i :tono :➘)
                            (:s :semiminima)
                            ;; bar 13
                            (:i :tono)
                            (:s :minima)
                            (:i :semitono-maggiore)
                            (:s :semibrevis)
                            (:i :semitono-maggiore :➘)
                            (:s :minima)
                            ;; bar 14
                            (:i :semitono-maggiore)
                            (:s :minima)
                            (:i :quinta :➘)
                            (:s :semibrevis)
                            (:i :tono)
                            (:s :minima)
                            ;; bar 15
                            (:i :tono)
                            (:s :minima :dot)
                            (:i :tono)
                            (:s :semiminima)
                            (:i :semitono-maggiore)
                            (:s :minima)
                            (:i :terza-minore :➘)
                            (:s :minima)
                            ;; bar 16
                            (:i :terza-minore)
                            (:s :minima)
                            (:i :tono)
                            (:s :minima)
                            (:i :terza-minore :➘)
                            (:s :semibrevis)
                            (:i :tono :➘)
                            (:s :semibrevis))
                           (:altus
                            (:t :semibrevis)
                            (:i :quinta)
                            (:s :brevis :word)
                            (:s :semibrevis :dot :sillable)
                            (:i :tono :➘)
                            (:s :minima :sillable)
                            (:s :brevis :sillable)
                            (:i :semitono-maggiore :➘)
                            (:s :brevis)
                            (:i :terza-minore)
                            (:s :semibrevis :dot)
                            (:i :tono :➘)
                            (:s :minima)
                            (:s :brevis)
                            (:i :semitono-maggiore :➘)
                            (:s :brevis)
                            (:i :tono :➘)
                            (:s :semibrevis)
                            ;; bar 9
                            (:s :semibrevis)
                            (:i :terza-maggiore :➘)
                            (:s :semibrevis)
                            (:i :quinta)
                            (:s :brevis)
                            ;; bar 11
                            (:t :semibrevis)
                            (:s :semibrevis)
                            ;; bar 12
                            (:i :tono)
                            (:s :minima)
                            (:i :tono)
                            (:s :semibrevis)
                            (:i :tono :➘)
                            (:s :minima)
                            ;; bar 13
                            (:i :tono)
                            (:s :minima)
                            (:s :minima)
                            (:i :tono :➘)
                            (:s :minima :dot)
                            (:i :tono :➘)
                            (:s :semiminima)
                            ;; bar 14
                            (:i :terza-minore :➘)
                            (:s :minima)
                            (:i :terza-minore)
                            (:s :minima)
                            (:i :tono)
                            (:s :minima)
                            (:i :tono)
                            (:s :semibrevis)
                            (:i :tono :➘)
                            (:s :minima)
                            (:i :tono)
                            (:s :semibrevis)
                            ;; bar 16
                            (:s :minima)
                            (:i :semitono-maggiore)
                            (:s :semibrevis)
                            (:i :semitono-maggiore :➘) ; correction
                            (:s :semiminima)
                            (:i :tono :➘)
                            (:s :semiminima)
                            ;; bar 17
                            (:i :tono :➘)
                            (:s :minima))
                           (:cantus
                            (:t :longa :dot)
                            (:i :ottava)
                            (:s :brevis :word)
                            (:s :semibrevis :dot :sillable)
                            (:i :tono :➘)
                            (:s :minima :sillable)
                            (:s :brevis :sillable)
                            (:i :semitono-maggiore :➘)
                            (:s :brevis :sillable)
                            (:i :tono :➘)
                            (:s :brevis)
                            ;; bar 9
                            (:i :terza-minore)
                            (:s :semibrevis :dot)
                            (:i :semitono-maggiore :➘)
                            (:s :semiminima)
                            (:i :tono :➘)
                            (:s :semiminima)
                            ;; bar 10
                            (:i :tono)
                            (:s :minima)
                            (:i :semitono-maggiore)
                            (:s :semibrevis)
                            (:i :semitono-maggiore :➘)
                            (:s :minima)
                            ;; bar 11
                            (:i :semitono-maggiore)
                            (:s :semibrevis)
                            (:t :minima)
                            (:s :semibrevis)
                            (:i :tono)
                            (:s :minima)
                            (:i :tono)
                            (:s :semibrevis)
                            ;; bar 13
                            (:i :tono :➘)
                            (:s :brevis)
                            ;; bar 14
                            (:t :minima)
                            (:i :tono)
                            (:s :minima :dot)
                            (:i :tono)
                            (:s :semiminima)
                            (:i :semitono-maggiore)
                            (:s :semibrevis)
                            (:i :semitono-maggiore :➘)
                            (:s :semiminima)
                            (:i :tono :➘)
                            (:s :semiminima)
                            (:i :tono :➘)
                            (:s :minima)
                            (:i :quarta)
                            (:s :minima :dot)
                            (:i :semitono-maggiore :➘)
                            (:s :semiminima)
                            (:i :tono :➘)
                            (:s :semibrevis)
                            (:i :semitono-maggiore :➘) ; ficta, notated :tono
                            (:s :minima)
                            ;; bar 17
                            (:i :semitono-maggiore) ; ficta, notated :tono
                            (:s :semibrevis))))

(defparameter *soave* '((:soprano
                         ;; Soav'e dolc' ardore,
                         (:s :brevis :word)
                         (:i :semitono-minore :➘)
                         (:s :semibrevis :dot :sillable)
                         (:s :minima :sillable)
                         (:i :diesis-minore :➘)
                         (:s :semibrevis :word)
                         (:s :semibrevis :word)
                         (:i :tono-minore)
                         (:s :brevis :sillable)
                         (:i :tono-minore)
                         (:s :semibrevis :sillable)
                         ;; %%
                         (:t :semibrevis)
                         (:i :terza-minima :➘)
                         (:s :semibrevis :word)
                         (:s :minima :sillable)
                         (:s :minima :sillable)
                         (:i :semitono-minore)
                         (:s :minima :word)
                         (:s :minima :word)
                         (:i :terza-minore :➘)
                         (:s :semibrevis :sillable)
                         (:i :quarta-propinqua)
                         (:s :semibrevis :sillable)
                         ;; che fra piant' e sospiri
                         (:t :semibrevis)
                         (:i :terza-minore :➘)
                         (:s :semibrevis :word)
                         (:i :tono-minore)
                         (:s :semibrevis :word)
                         (:i :diesis-minore :➘)
                         (:s :minima :word)
                         (:i :semitono-minore)
                         (:s :semibrevis :word)
                         (:s :minima :word)
                         (:i :semitono-minore)
                         (:s :semibrevis :sillable)
                         (:i :quarta :➘)
                         (:s :semibrevis :sillable)
                         ;; %%
                         (:t :minima)
                         (:i :diesis-minore)
                         (:s :semibrevis :word)
                         (:s :minima :word)
                         (:i :semitono-minore)
                         (:s :minima :word)
                         (:i :semitono-minore)
                         (:s :minima :word)
                         (:i :diesis-minore)
                         (:s :minima :word)
                         (:i :quarta)
                         (:s :semibrevis :sillable)
                         (:i :semitono-maggiore :➘)
                         (:s :semibrevis)
                         (:i :semitono-minore)
                         (:s :semibrevis :sillable)
                         (:t :brevis))
                        (:alto
                         (:t :brevis)
                         (:i :quarta-minima :➘)
                         (:s :brevis :word)
                         (:i :diesis-minore)
                         (:s :semibrevis :dot :sillable)
                         (:s :minima :sillable)
                         (:i :tono-minore)
                         (:s :semibrevis :word)
                         (:s :semibrevis :word)
                         (:i :terza-più-di-maggiore :➘)
                         (:s :minima :dot :sillable)
                         (:i :semitono-maggiore :➘)
                         (:s :semiminima)
                         (:i :tono :➘)
                         (:s :semibrevis)
                         (:i :diesis-minore)
                         (:s :brevis :sillable)
                         ;; %%
                         (:t :semibrevis)
                         (:i :settima-minima)
                         (:s :semibrevis :word)
                         (:i :semitono-minore :➘)
                         (:s :minima :dot :sillable)
                         (:s :semiminima :sillable)
                         (:i :diesis-minore :➘)
                         (:s :minima :word)
                         (:s :minima :word)
                         (:i :quinta-imperfetta-propinqua :➘)
                         (:s :semibrevis :sillable)
                         (:i :diesis-minore :➘)
                         (:s :semibrevis :sillable)
                         ;; che fra piant' e sospiri
                         (:t :minima)
                         (:i :quarta-propinqua)
                         (:s :semibrevis :word)
                         (:s :minima :word)
                         (:i :terza-maggiore-propinqua :➘)
                         (:s :semibrevis :word)
                         (:s :minima :word)
                         (:i :quarta :➘)
                         (:s :minima :word)
                         (:i :semitono-maggiore)
                         (:s :semibrevis :sillable)
                         (:i :semitono-maggiore)
                         (:s :semibrevis)
                         (:i :diesis-minore :➘)
                         (:s :semibrevis :sillable)
                         ;; che fra piant' e
                         (:t :minima)
                         (:i :terza-minima :➘)
                         (:s :semibrevis :word)
                         (:s :minima :word)
                         (:i :diesis-minore :➘)
                         (:s :minima :word)
                         (:i :ottava)
                         (:s :minima :word)
                         (:t :brevis))
                        (:tenore
                         (:t :longa)
                         (:i :sesta-minore :➘)
                         (:s :brevis :word)
                         (:i :diesis-minore)
                         (:s :semibrevis :dot :sillable)
                         (:i :semitono-maggiore)
                         (:s :minima :sillable)
                         (:i :terza-più-di-minore :➘)
                         (:s :minima :dot :word)
                         (:i :tono)
                         (:s :semiminima)
                         (:i :semitono-maggiore)
                         (:s :minima)
                         (:i :terza-minore :➘)
                         (:s :minima :word)
                         (:i :quarta-propinqua)
                         (:s :brevis :sillable)
                         (:i :terza-più-di-maggiore :➘)
                         (:s :semibrevis :sillable)
                         ;; %%
                         (:t :semibrevis)
                         (:i :terza-più-di-maggiore)
                         (:s :semibrevis :word)
                         (:i :diesis-minore)
                         (:s :minima :dot :sillable)
                         (:s :semiminima :sillable)
                         (:i :diesis-minore)
                         (:s :minima :word)
                         (:s :minima :word)
                         (:i :semitono-minore)
                         (:s :semibrevis :sillable)
                         (:i :quarta-minima :➘)
                         (:s :brevis :sillable)
                         ;; che fra piant' e sospiri
                         (:t :minima)
                         (:i :tono-maggiore :➘)
                         (:s :semibrevis :word)
                         (:i :terza-minore)
                         (:s :minima :word)
                         (:i :semitono-minore :➘)
                         (:s :semibrevis :word)
                         (:i :tono)
                         (:s :minima :word)
                         (:s :minima :word)
                         (:i :semitono-minore)
                         (:s :semibrevis :sillable)
                         (:i :semitono-maggiore)
                         (:s :minima :sillable)
                         ;; che fra piant' e
                         (:i :semitono-minore :➘)
                         (:s :minima :sillable)
                         (:i :semitono-maggiore :➘)
                         (:s :semibrevis :word)
                         (:i :semitono-minore)
                         (:s :minima :word)
                         (:i :semitono-minore)
                         (:s :minima :word)
                         (:t :brevis))
                        (:basso
                         (:t :longa :dot)
                         (:i :ottava :➘)
                         (:i :terza-minima :➘)
                         (:s :brevis :word)
                         (:i :semitono-minore)
                         (:s :semibrevis :dot :sillable)
                         (:s :minima :sillable)
                         (:i :terza-minima :➘)
                         (:s :semibrevis :dot :word)
                         (:s :minima :word)
                         (:i :semitono-minore)
                         (:s :semibrevis :sillable)
                         (:i :terza-minore :➘)
                         (:s :semibrevis :sillable)
                         ;; %%
                         (:t :semibrevis)
                         (:i :semitono-maggiore :➘)
                         (:s :semibrevis :word)
                         (:i :diesis-minore)
                         (:s :minima :dot :sillable)
                         (:s :semiminima :sillable)
                         (:i :quarta-minima)
                         (:s :minima :word)
                         (:s :minima :word)
                         (:i :diesis-minore)
                         (:s :brevis :sillable)
                         (:i :semitono-minore)
                         (:s :semibrevis :sillable)
                         ;; che fra pianti e sospiri
                         (:t :minima)
                         (:i :quarta :➘)
                         (:s :minima :word)
                         (:i :terza-più-di-maggiore)
                         (:s :minima :word)
                         (:s :minima :word)
                         (:i :quinta :➘)
                         (:s :minima :sillable)
                         (:s :minima :word)
                         (:i :quarta-minima)
                         (:s :semibrevis :sillable)
                         (:i :terza-minima :➘)
                         (:s :semibrevis :sillable)
                         ;; pian-
                         (:t :semibrevis)
                         (:i :diesis-minore :➘)
                         (:s :semibrevis :word)
                         (:t :brevis))))
